name: Deploy

on:
  push:
    branches:
      - main
      - feature/TERRA-37_github_page

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: gh-pages/package-lock.json
      - run: cd gh-pages
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

      - run: cd ..

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages/docs/.vitepress/dist
