name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: actions/setup-python@v3
      - name: Install dependencies SEE https://github.com/antonbabenko/pre-commit-terraform#1-install-dependencies
        run: |
          brew install pre-commit terraform-docs tflint tfsec checkov terrascan
      #- uses: pre-commit/action@v3.0.0
      - name: Execute pre-commit https://github.com/pre-commit/action/blob/main/action.yml
        run: |
          pre-commit run --all-files --verbose --color=always --show-diff-on-failure
